# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    set ::env(RT_TMP) "./.Xil/Vivado-2840-EddieRichter-PC/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a100tcsg324-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog {
      {C:/Users/Eddie Richter/Desktop/ECE 369/LAB1-3/Lab1/Lab1.srcs/sources_1/new/ProgramCounter.v}
      {C:/Users/Eddie Richter/Desktop/ECE 369/LAB1-3/Lab1/Lab1.srcs/sources_1/new/SevenSegment.v}
      {C:/Users/Eddie Richter/Desktop/ECE 369/LAB1-3/Lab1/Lab1.srcs/sources_1/new/PCAdder.v}
      {C:/Users/Eddie Richter/Desktop/ECE 369/LAB1-3/Lab1/Lab1.srcs/sources_1/new/InstructionMemory.v}
      {C:/Users/Eddie Richter/Desktop/ECE 369/LAB1-3/Lab1/Lab1.srcs/sources_1/new/LoReg.v}
      {C:/Users/Eddie Richter/Desktop/ECE 369/LAB1-3/Lab1/Lab1.srcs/sources_1/new/HiReg.v}
      {C:/Users/Eddie Richter/Desktop/ECE 369/LAB1-3/Lab1/Lab1.srcs/sources_1/new/Two4DigitDisplay.v}
      {C:/Users/Eddie Richter/Desktop/ECE 369/LAB1-3/Lab1/Lab1.srcs/sources_1/new/SignExtension.v}
      {C:/Users/Eddie Richter/Desktop/ECE 369/LAB1-3/Lab1/Lab1.srcs/sources_1/new/RegisterFile.v}
      {C:/Users/Eddie Richter/Desktop/ECE 369/LAB1-3/Lab1/Lab1.srcs/sources_1/new/Mux32Bit2To1.v}
      {C:/Users/Eddie Richter/Desktop/ECE 369/LAB1-3/Lab1/Lab1.srcs/sources_1/new/InstructionFetchUnit.v}
      {C:/Users/Eddie Richter/Desktop/ECE 369/LAB1-3/Lab1/Lab1.srcs/sources_1/new/DataMemory.v}
      {C:/Users/Eddie Richter/Desktop/ECE 369/LAB1-3/Lab1/Lab1.srcs/sources_1/new/Controller.v}
      {C:/Users/Eddie Richter/Desktop/ECE 369/LAB1-3/Lab1/Lab1.srcs/sources_1/new/ALU32Bit.v}
      {C:/Users/Eddie Richter/Desktop/ECE 369/LAB1-3/Lab1/Lab1.srcs/sources_1/new/top.v}
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top top
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-2840-EddieRichter-PC/"
    if {$rt::useElabCache == false} {
      rt::run_rtlelab -module $rt::top
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
    }


    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
