# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Eddie Richter/Desktop/ECE 369/LAB1-3/Lab1/Lab1.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Eddie Richter/Desktop/ECE 369/LAB1-3/Lab1/Lab1.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/Eddie Richter/Desktop/ECE 369/LAB1-3/Lab1/Lab1.srcs/sources_1/new/SevenSegment.v}
  {C:/Users/Eddie Richter/Desktop/ECE 369/LAB1-3/Lab1/Lab1.srcs/sources_1/new/ZeroCompSometimes.v}
  {C:/Users/Eddie Richter/Desktop/ECE 369/LAB1-3/Lab1/Lab1.srcs/sources_1/new/Two4DigitDisplay.v}
  {C:/Users/Eddie Richter/Desktop/ECE 369/LAB1-3/Lab1/Lab1.srcs/sources_1/new/SignExtension.v}
  {C:/Users/Eddie Richter/Desktop/ECE 369/LAB1-3/Lab1/Lab1.srcs/sources_1/new/SignExtendRegister.v}
  {C:/Users/Eddie Richter/Desktop/ECE 369/LAB1-3/Lab1/Lab1.srcs/sources_1/new/RegisterFile.v}
  {C:/Users/Eddie Richter/Desktop/ECE 369/LAB1-3/Lab1/Lab1.srcs/sources_1/new/Reg32Bit.v}
  {C:/Users/Eddie Richter/Desktop/ECE 369/LAB1-3/Lab1/Lab1.srcs/sources_1/new/Mux5Bit2To1.v}
  {C:/Users/Eddie Richter/Desktop/ECE 369/LAB1-3/Lab1/Lab1.srcs/sources_1/new/Mux32Bit2To1.v}
  {C:/Users/Eddie Richter/Desktop/ECE 369/LAB1-3/Lab1/Lab1.srcs/sources_1/new/HiLoArith.v}
  {C:/Users/Eddie Richter/Desktop/ECE 369/LAB1-3/Lab1/Lab1.srcs/sources_1/new/DataMemory.v}
  {C:/Users/Eddie Richter/Desktop/ECE 369/LAB1-3/Lab1/Lab1.srcs/sources_1/new/Controller.v}
  {C:/Users/Eddie Richter/Desktop/ECE 369/LAB1-3/Lab1/Lab1.srcs/sources_1/new/ClkDiv.v}
  {C:/Users/Eddie Richter/Desktop/ECE 369/LAB1-3/Lab1/Lab1.srcs/sources_1/new/BranchControl.v}
  {C:/Users/Eddie Richter/Desktop/ECE 369/LAB1-3/Lab1/Lab1.srcs/sources_1/new/ALU32Bit.v}
  {C:/Users/Eddie Richter/Desktop/ECE 369/LAB1-3/Lab1/Lab1.srcs/sources_1/new/ProgramCounter.v}
  {C:/Users/Eddie Richter/Desktop/ECE 369/LAB1-3/Lab1/Lab1.srcs/sources_1/new/PCAdder.v}
  {C:/Users/Eddie Richter/Desktop/ECE 369/LAB1-3/Lab1/Lab1.srcs/sources_1/new/InstructionMemory.v}
  {C:/Users/Eddie Richter/Desktop/ECE 369/LAB1-3/Lab1/Lab1.srcs/sources_1/new/top.v}
}
read_xdc {{C:/Users/Eddie Richter/Desktop/ECE 369/LAB1-3/Lab1/Lab1.srcs/constrs_1/new/Two4DigitDisplay.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Eddie Richter/Desktop/ECE 369/LAB1-3/Lab1/Lab1.srcs/constrs_1/new/Two4DigitDisplay.xdc}}]

synth_design -top top -part xc7a100tcsg324-1
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
